config/routes.rb
EatenAteEat::Application.routes.draw do
  resources :chefs

  resources :deserts 
  root "deserts#index"

  

end

app/models/chef.rb
class Chef < ActiveRecord::Base
	validates :name, presence: true
	has_many :deserts

end

app/models/desert.rb
class Desert < ActiveRecord::Base
	belongs_to :chef
	validates :name, presence: true
	validates :recipe, presence: true
	validates :instruction, presence: true
	validates :img_url, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
  	I18n.locale = params[:locale] || I18n.default_locale
  end
  
  def default_url_options(options={})
  	logger.debug "default_url_options is passed options: #{options.inspect}\n"
  	{ locale: I18n.locale }
  end

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:show, :edit, :update, :destroy]

  # GET /chefs
  # GET /chefs.json
  def index
    @chefs = Chef.all
  end

  # GET /chefs/1
  # GET /chefs/1.json
  def show
  end

  # GET /chefs/new
  def new
    @chef = Chef.new
  end

  # GET /chefs/1/edit
  def edit
  end

  # POST /chefs
  # POST /chefs.json
  def create
    @chef = Chef.new(chef_params)

    respond_to do |format|
      if @chef.save
        format.html { redirect_to @desert, notice: 'Chef was successfully created.' }
        # format.html { redirect_to @desert }
        # format.json { render action: 'show', status: :created, location: @chef }
      else
        format.html { render action: 'new' }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chefs/1
  # PATCH/PUT /chefs/1.json
  def update
    respond_to do |format|
      if @chef.update(chef_params)
        format.html { redirect_to @chef, notice: 'Chef was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chefs/1
  # DELETE /chefs/1.json
  def destroy
    @chef.destroy
    respond_to do |format|
      format.html { redirect_to chefs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chef
      @chef = Chef.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chef_params
      params.require(:chef).permit(:name)
    end
end

app/controllers/deserts_controller.rb
class DesertsController < ApplicationController
  before_action :set_desert, only: [:show, :edit, :update, :destroy]

  # GET /deserts
  # GET /deserts.json
  def index
    @deserts = Desert.paginate(page: params[:page],per_page: 3,  :conditions => ['name LIKE ?', "%#{params[:search]}%"])

  end

  # GET /deserts/1
  # GET /deserts/1.json
  def show
  end

  # GET /deserts/new
  def new
    @desert = Desert.new
  end

  # GET /deserts/1/edit
  def edit
  end

  # POST /deserts
  # POST /deserts.json
  def create
    @desert = Desert.new(desert_params)

    respond_to do |format|
      if @desert.save
        format.html { redirect_to @desert, notice: 'Desert was successfully created.' }
        format.json { render action: 'show', status: :created, location: @desert }
      else
        format.html { render action: 'new' }
        format.json { render json: @desert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deserts/1
  # PATCH/PUT /deserts/1.json
  def update
    respond_to do |format|
      if @desert.update(desert_params)
        format.html { redirect_to @desert, notice: 'Desert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @desert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deserts/1
  # DELETE /deserts/1.json
  def destroy
    @desert.destroy
    respond_to do |format|
      format.html { redirect_to deserts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desert
      @desert = Desert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def desert_params
      params.require(:desert).permit(:name, :recipe, :instruction, :img_url, :chef_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chef_helper.rb
module ChefHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/deserts_helper.rb
module DesertsHelper
end

app/views/chefs/_form.html.erb
<%= form_for(@chef) do |f| %>
  <% if @chef.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chef.errors.count, "error") %> prohibited this chef from being saved:</h2>

      <ul>
      <% @chef.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <button type="submit" class = "radius button" >  <%= t('create') %> </button>
  </div>
<% end %>

app/views/chefs/edit.html.erb
<h1>Editing chef</h1>

<%= render 'form' %>

<%= link_to 'Show', @chef %> |
<%= link_to 'Back', chefs_path %>

app/views/chefs/index.html.erb
<h1>Listing chefs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @chefs.each do |chef| %>
      <tr>
        <td><%= chef.name %></td>
        <td><%= link_to 'Show', chef %></td>
        <td><%= link_to 'Edit', edit_chef_path(chef) %></td>
        <td><%= link_to 'Destroy', chef, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chef', new_chef_path %>

app/views/chefs/new.html.erb
<h1>New chef</h1>

<%= render 'form' %>

<%= link_to 'Back', deserts_path %>

app/views/chefs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel radius">

<p>
  <strong>Name:</strong>
  <%= @chef.name %>
</p>
</div>


<%= link_to 'Edit', edit_chef_path(@chef) %> |
<%= link_to 'Back', deserts_path %>

app/views/deserts/_form.html.erb
<%= form_for(@desert) do |f| %>
<form>
    <% if @desert.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@desert.errors.count, "error") %> prohibited this desert from being saved:</h2>

        <ul>
        <% @desert.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :recipe %><br>
      <%= f.text_area :recipe %>
    </div>
    <div class="field">
      <%= f.label :instruction %><br>
      <%= f.text_area :instruction %>
    </div>
    <div class="field">
      <%= f.label :img_url %><br>
      <%= f.text_field :img_url %>

    </div>
    <div class="field">
      <%= f.label :chef_id %><br>
      <%= f.collection_select :chef_id, Chef.all,:id,:name ,
      {prompt: true, length: 25},{style: "width: 180px;" , class: "customDropdown" }
      %>
    </div>
    <button type="submit" class = "radius button" >  Create </button>
      
    </div>

</form>

<% end %>

app/views/deserts/_slider.html.erb
 <div class="hide-for-small">
        <div id="featured">
              <ul data-orbit data-options="timer_speed:2500; bullets:false;">

              <img src="http://s24.postimg.org/ryzb5j46t/Custard.png" alt="slide image">
              <img src="http://s24.postimg.org/cqn5x0h8l/cheese_Cake.png" alt="slide image">
          </div>
        </div>
 

app/views/deserts/edit.html.erb
<h1>Editing desert</h1>

<%= render 'form' %>

<%= link_to 'Show', @desert %> |
<%= link_to 'Back', deserts_path %>

app/views/deserts/index.html.erb
  <tbody> 
 
 
  <div class="row">
    <div class="large-12 columns">
 
    <!-- Desktop Slider -->
 
     <%= render "deserts/slider" %>
    <!-- End Desktop Slider -->
 
 
    <!-- Mobile Header -->
 
 
    <div class="row">
      <div class="small-12 show-for-small"><br>
        <%= image_tag "macarons.png" %>
      </div>
    </div>
 
 
  <!-- End Mobile Header -->
 
    </div>
  </div><br>
 
  <div class="row">
    <div class="large-12 columns">
      <div class="row">
 
    <!-- Thumbnails -->
    <% @deserts.each do |desert| %>
        <div class="large-4 small-6 columns ">
          <!-- <div class="img-resize" href= desert > <img src= <%= desert.img_url %> > </div> -->
          <div class="img-resize">
            <%= link_to image_tag(desert.img_url), desert%>
          </div>
          <h6 class="panel radius subheader"><%= link_to t(desert.name), desert %></h6>
          <!-- <h6 class="panel radius subheader"> <%=desert.name%> </h6> -->
        </div>
                
    <% end %>

 
    <!-- End Thumbnails -->
 
      </div>
                 <div class="right" ><%= will_paginate @deserts %><br></div> 

    </div>
  </div>
 
 
 
  <div class="row">
    <div class="large-12 columns">
      <div class="row">
 
    <!-- Content -->
 
        <div class="large-8 columns">
          <div class="panel radius">
 
          <div class="row">
          <div class="large-6 small-6 columns">
 
            <h4><%= t('topbarTitle') %></h4><hr/>
            <h5 class="subheader"> <%= t('desLeft') %>
            </h5>
 
 
          </div>
          <div class="large-6 small-6 columns">
 
            <p><%= t('desRight') %></p>
        </div>
 
          </div>
          </div>
        </div>
 
          <div class="large-4 columns hide-for-small">
 
          <h4><%= t('createMenu') %></h4><hr/>
 
          <a class="large button expand" href="deserts/new">
            <%= t('createMenu') %>
          </a>
 
          <a class="large button expand" href="chefs/new">
            <%= t('createChef') %>
          </a>
 



              <%= form_tag deserts_path, :method => 'get' do %>
                  <%= text_field_tag :search, params[:search],placeholder: t("searchField") %>
                  <div class = "right">
                    <%= submit_tag t("searchField") , :class => "button round" %>
                  </div>
              <% end %>
            
 
        </div>
 
    <!-- End Content -->
 
      </div>
    </div>
  </div>
  </tbody>

app/views/deserts/new.html.erb
<h1><%= t('newDesert') %></h1>

<%= render 'form' %>

<%= link_to 'Back', deserts_path %>

app/views/deserts/show.html.erb
  <tbody>
    <div class="row" align="center">
      <img src=<%=@desert.img_url%>> 
    </div>
  </tbody>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @desert.name %>
</p>

<p>
  
</p>
<div class="panel radius">
<p>
  <strong>Recipe:</strong>
  <%= simple_format(h @desert.recipe) %>

</p>
</div>

<p>
  <div class="panel radius">
    <strong>Instruction:</strong>
    <%= simple_format(h @desert.instruction) %>
  </div>
</p>


<p>
  <strong>Chef:</strong>
  <%= @desert.chef.name %>
</p>

<%= link_to 'Edit', edit_desert_path(@desert) %> |
<%= link_to 'Back', deserts_path %> |
<%= link_to 'Delete', @desert, method: :delete, data: { confirm: 'Are you sure to delete this ?' } %>

app/views/layouts/_footer.html.erb
    <!-- Footer -->
 
  <footer class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-6 columns">
          <p>&copy; Copyright , Created by Promboon Jirawattanakitja 5410404441.</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="/">Home</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<div class="large-12 sticky ">
 
    <!-- Navigation -->
      <nav class="top-bar ">
        <ul class="title-area">
          <!-- Title Area -->
          <li class="name">
            <h1>
              <a href="/">
                <%= t('topbarTitle') %>
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
 
        <section class="top-bar-section">
          <ul class="left">
            <li class = "divider"> <li> <%= link_to "Eng", :locale => 'en' %> </li> </li> 
            <li class = "divider"> <li> <%= link_to "Thai", :locale => 'th' %> </li></li> 

          </ul>
          
 
        </section>
      </nav>
 
    <!-- End Navigation -->
  
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "EatAteEaten" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
          <%=render 'layouts/header'%>

    <div class="large-12 columns">
     
      <%= yield %>
      <%= render 'layouts/footer'%>
     
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>